/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef time_CONSTANTS_H
#define time_CONSTANTS_H

#include "time_types.h"



class timeConstants {
 public:
  timeConstants();

};

extern const timeConstants g_time_constants;



#endif
